# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ mc/1.18 ]
    paths:
      - 'changelog.md'
      - 'build.properties' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.16
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew build versionTxt
        echo "::set-output name=artifactversion::`basename \`cat ./build/libs/version.txt\``"
        echo "::set-output name=artifactname::`basename \`cat ./build/libs/artifact.txt\``"
        echo "::set-output name=artifactfullname::`realpath ./build/libs/\`cat ./build/libs/artifact.txt\``"
        echo "::set-output name=mcversion::`basename ${{ github.ref }}`"
      id: build
    - name: Create release with files
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "${{ steps.build.outputs.mcversion }}-${{ steps.build.outputs.artifactversion }}"
        name: Release ${{ steps.build.outputs.artifactversion }}
        body_path: changelog.md
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_unmatched_files: true
        files: |
          ${{ steps.build.outputs.artifactfullname }}