# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      deploy_curseforge:
        description: 'Deploy to Curseforge'
        type: boolean
        default: false
      deploy_modrinth:
        description: 'Deploy to Modrinth'
        type: boolean
        default: false
  push:
    branches: [ mc/1.18 ]
    paths:
      - 'changelog.md'
      - 'build.properties' 

env:
  CURSEFORGE_ID: ${{ fromJSON('["", "254268"]')[github.event.inputs.deploy_curseforge == 'true'] }} 
  MODRINTH_ID: ${{ fromJSON('["", "Tl8ESrhX"]')[github.event.inputs.deploy_modrinth == 'true'] }}
  JAVA_VERSION: 17

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.${{ env.JAVA_VERSION }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew build versionTxt
        echo "::set-output name=artifactversion::`basename \`cat ./build/libs/version.txt\``"
        echo "::set-output name=artifactname::`basename \`cat ./build/libs/artifact.txt\``"
        echo "::set-output name=artifactfullname::`realpath ./build/libs/\`cat ./build/libs/artifact.txt\``"
        echo "::set-output name=mcversion::`basename ${{ github.ref }}`"
      id: build
      
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: "mc${{ steps.build.outputs.mcversion }}-${{ steps.build.outputs.artifactversion }}"
        message: "Torchmaster ${{ steps.build.outputs.artifactversion }} for Minecraft ${{ steps.build.outputs.mcversion }}"
      
    - uses: Kir-Antipov/mc-publish@v2.1
      with:
        modrinth-id: ${{ env.MODRINTH_ID }}
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        curseforge-id: ${{ env.CURSEFORGE_ID }} 
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        github-tag: "mc${{ steps.build.outputs.mcversion }}-${{ steps.build.outputs.artifactversion }}"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        files-primary: build/libs/!(*-@(dev|sources)).jar
        #files-secondary: build/libs/*-@(dev|sources).jar
        name: Torchmaster ${{ steps.build.outputs.artifactversion }} for Minecraft ${{ steps.build.outputs.mcversion }}
        version: ${{ steps.build.outputs.artifactversion }}
        version-type: release
        changelog-file: changelog.md
        loaders: forge
        game-versions: ${{ steps.build.outputs.mcversion }}
        version-resolver: releasesIfAny
        java: ${{ env.JAVA_VERSION }}
        retry-attempts: 2
        retry-delay: 10000
