# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      deploy_curseforge:
        description: 'Deploy to Curseforge'
        type: boolean
        default: false
      deploy_modrinth:
        description: 'Deploy to Modrinth'
        type: boolean
        default: false
      create_github_release:
        description: 'Create Github Release'
        type: boolean
        default: false

env:
  JAVA_VERSION: 17

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.${{ env.JAVA_VERSION }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      id: gradle_build
      run: |
        ./gradlew build versionTxt
        echo "::set-output name=artifactversion::`basename \`cat ./build/libs/version.txt\``"
        echo "::set-output name=artifactname::`basename \`cat ./build/libs/artifact.txt\``"
        echo "::set-output name=artifactfullname::`realpath ./build/libs/\`cat ./build/libs/artifact.txt\``"
        echo "::set-output name=mcversion::`basename ${{ github.ref }}`"
        echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        if [[ `cat ./build/libs/version.txt` == *-alpha ]]
        then
          echo "::set-output name=releasetype::alpha"
        elif [[ `cat ./build/libs/version.txt` == *-beta ]]
        then
          echo "::set-output name=releasetype::beta"
        else
          echo "::set-output name=releasetype::release"
        fi

    - name: debug_print
      run: |
        echo "!cancelled() == ${{ !cancelled() }}"
        echo "needs.gradle_build.result == '${{ needs.gradle_build.result }}'"
        echo "github.event.inputs.create_github_release == '${{ github.event.inputs.create_github_release }}'"
        echo "Result: ${{ !cancelled() && needs.gradle_build.result == 'success' && github.event.inputs.create_github_release == 'true' }}"
      
    - name: Create Github Release
      id: create_github_release
      if: ${{ !cancelled() && needs.gradle_build.result == 'success' && github.event.inputs.create_github_release == 'true' }}
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "changelog.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "${{ steps.build.outputs.artifactfullname }}"
        tag: "mc${{ steps.build.outputs.mcversion }}-${{ steps.build.outputs.artifactversion }}"

      
    - name: Publish to Modrinth
      id: publish_modrinth
      if: ${{ !cancelled() && needs.gradle_build.result == 'success' && github.event.inputs.deploy_modrinth == 'true' }}
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: "Tl8ESrhX"
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        files-primary: ${{ steps.build.outputs.artifactfullname }}
        name: torchmaster-${{ steps.build.outputs.artifactversion }}
        version: ${{ steps.build.outputs.artifactversion }}
        version-type: ${{ steps.build.outputs.releasetype }}
        changelog-file: changelog.md
        loaders: forge
        game-versions: ${{ steps.build.outputs.mcversion }}
        java: ${{ env.JAVA_VERSION }}

    - name: Publish to Curseforge
      id: publish_curseforge
      if: ${{ !cancelled() && needs.gradle_build.result == 'success' && github.event.inputs.deploy_curseforge == 'true' }}
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        curseforge-id: "254268"
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        files-primary: ${{ steps.build.outputs.artifactfullname }}
        name: torchmaster-${{ steps.build.outputs.artifactversion }}
        version: ${{ steps.build.outputs.artifactversion }}
        version-type: ${{ steps.build.outputs.releasetype }}
        changelog-file: changelog.md
        loaders: forge
        game-versions: ${{ steps.build.outputs.mcversion }}
        java: ${{ env.JAVA_VERSION }}
